# Note: each job is in a separate workflow to support individual CI badges in the readme
name: Iron

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /root
  # Coupled with our use of the test_log crate this should give us good CI output on failure
  RUST_LOG: debug

jobs:
  iron:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: carter12s/roslibrust-ci-iron:rust_1_90
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Lint
        run: source /root/.cargo/env; cargo fmt --all -- --check
      - name: Start rosbridge
        run: source /opt/ros/iron/setup.bash; ros2 launch rosbridge_server rosbridge_websocket_launch.xml & disown; ros2 run rosapi rosapi_node & sleep 1
      - name: Integration Tests
        run: source /root/.cargo/env; cargo test --features ros2_test -- --test-threads 1